name: Terraform Apply

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: 9ae3847d-fba1-4eb3-a7d2-78779638840e
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: 3c286043-98c2-4679-aa9a-de40490ad27a
      ARM_TENANT_ID: a88ae17f-e646-4b80-a909-25db6b749d30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Log In To Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
